name: ' Jaaks Test Site'
favicon: null
layout_spectrum: 0.10276310751214623
typography_spectrum: 0.6096469420008361
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#00c2e8'
    - '#9f9f9f'
    - '#343434'
  brandStrength: 0.878029927611351
  lightness: 0.25209417659789324
  saturation: 0.6936826584860682
  rhythmicContrast: 0.6814497651066631
purpose: []
